# Site settings
title: JVBlog
description: 'Information, musings, and projects on cyber security'
url: 'https://jvbond.github.io'
baseurl: 

author:
  name: 'Jeff Bond'
  twitter_username: 
  facebook_username: 
  github_username:  jvbond
  linkedin_username:  jvbond

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  
prose:
  rooturl: '_posts'
  siteurl: 'http://jvbond.github.io'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Title HERE"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Headline here"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Security"
              value: security
            - name: "OSCP"
              value: oscp
            - name: "Code"
              value: code
          alterable: true


gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

